

SELECT TOP 100 * FROM sys.tables WHERE name LIKE '%log%'


SELECT TOP 100 * FROM sys.columns 
WHERE 


SELECT    ORDINAL_POSITION  ,COLUMN_NAME  ,DATA_TYPE  ,CHARACTER_MAXIMUM_LENGTH  ,IS_NULLABLE  ,COLUMN_DEFAULT
FROM     INFORMATION_SCHEMA.COLUMNS 
WHERE     TABLE_NAME = 'Product' 
ORDER BY   ORDINAL_POSITION ASC; 


SELECT TABLE_NAME, Column_name, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS 
SELECT * FROM INFORMATION_SCHEMA.COLUMNS 

WHERE TABLE_NAME = 'Product' 
ORDER BY   ORDINAL_POSITION ASC; 
