
select SYSDATETIME(), SYSDATETIMEOFFSET(), SYSUTCDATETIME()

SELECT FORMAT(GETDATE() ,'yyyyMMddHHmmss')

--SELECT DATE_HASH('2023-09-01', 'SHA256') AS date_hash_sha256

SELECT SYSDATETIME(),SYSDATETIMEOFFSET(),SYSUTCDATETIME(),CURRENT_TIMESTAMP,GETDATE(),GETUTCDATE(); 