DBCC CHECKDB(N'master')  WITH NO_INFOMSGS
GO
DBCC CHECKDB(N'model')  WITH NO_INFOMSGS
GO
DBCC CHECKDB(N'msdb')  WITH NO_INFOMSGS
GO
DBCC CHECKDB(N'jenkins_cms_pullrequest')  WITH NO_INFOMSGS
GO
DBCC CHECKDB(N'Logging')  WITH NO_INFOMSGS
GO
DBCC CHECKDB(N'octopus')  WITH NO_INFOMSGS
GO
DBCC CHECKDB(N'BOG')  WITH NO_INFOMSGS
GO
DBCC CHECKDB(N'ProGet')  WITH NO_INFOMSGS
GO
DBCC CHECKDB(N'kraken')  WITH NO_INFOMSGS

